# Generated by Django 4.2 on 2025-12-08 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('portrait', 'Portrait Session'), ('wedding', 'Wedding Photoshoot'), ('product', 'Product Photography'), ('event', 'Event Coverage')], default='portrait', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='session_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 8, 10, 12, 2, 805510, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12),
        ),
    ]
