# Generated by Django 4.2 on 2025-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_created_at_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
