# Generated by Django 5.0.6 on 2026-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
